# -*- coding: utf-8 -*-
"""task1_10.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d3mwWqxS2QD-MM17SuFuSCiBkTfmbYyB
"""

import pandas as pd
df = pd.read_csv("/content/drive/My Drive/diamonds.csv")
print("The shape of original dataframe is",df.shape)
print("The remaining shape excluding dataframe containing any mising values(if any) is",df.dropna(how='any').shape)
print("\n")
if df.shape == df.dropna(how='any').shape:
  print(" Hence there are no missing values \n Therefore,the dataframe remains unchanged")
  print("\n")
  print(df)
else:
  df.dropna(how="any")
  df