# -*- coding: utf-8 -*-
"""task1_12.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kZj6rFkzXKgCljovVbgrsnOrG6ZedssO
"""

import pandas as pd
data=pd.read_csv("/content/drive/My Drive/diamonds.csv")
print("Original DataFrame")
print(data.shape)
print("Sample 75% of diamond datFrame's row without replacement:")
result= data.sample(frac=0.75, random_state=99)
print(result)
print("Remaining 25% of the row")
print(data.loc[data.index.isin(result.index),:])