# -*- coding: utf-8 -*-
"""task1_7.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1enlCjl0RFLbOV1DkC_LKYnICAak2dC5J
"""

import pandas as pd
df = pd.read_csv('diamonds.csv')
df.head(5)