# -*- coding: utf-8 -*-
"""task1_11.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_KuV5PHqxMdfvv6NM0LvvxADICNqqnac
"""

import pandas as pd
df = pd.read_csv("/content/drive/My Drive/diamonds.csv")
print("count of duplicated rows is as follows")
print(df.duplicated().sum())
print("for checking purpose,") 
print(df.duplicated())