# -*- coding: utf-8 -*-
"""task1_8.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZImCZ1tSeWTF8VeGjJK0xVOhkgDRavEr
"""

import pandas as pd
data= pd.read_csv("/content/drive/My Drive/diamonds.csv")
df=pd.DataFrame(data)
print (df.iloc[0:1])